export const tagColors: { [key: string]: string } = {
  // Programming Languages
  "JavaScript": "bg-yellow-500",
  "Python": "bg-blue-500",
  "Java": "bg-red-600",
  "C++": "bg-indigo-500",
  "Ruby": "bg-red-500",
  "Go": "bg-green-500",
  "TypeScript": "bg-blue-700",
  "PHP": "bg-purple-600",
  "Swift": "bg-orange-600",
  "Kotlin": "bg-teal-500",
  "Rust": "bg-amber-600",
  "Dart": "bg-blue-400",
  "Perl": "bg-gray-600",
  "C#": "bg-indigo-700",
  "R": "bg-green-700",

  // Web Development
  "React": "bg-blue-500",
  "Vue.js": "bg-green-600",
  "Angular": "bg-red-500",
  "Node.js": "bg-green-500",
  "HTML": "bg-orange-500",
  "CSS": "bg-indigo-500",
  "SASS/SCSS": "bg-pink-500",
  "Tailwind CSS": "bg-teal-500",
  "Bootstrap": "bg-blue-600",
  "jQuery": "bg-blue-800",
  "Next.js": "bg-black",
  "Nuxt.js": "bg-teal-400",
  "Ember.js": "bg-purple-600",
  "Backbone.js": "bg-gray-500",

  // Frameworks & Libraries
  "Express.js": "bg-gray-700",
  "Django": "bg-yellow-500",
  "Flask": "bg-gray-500",
  "Spring Boot": "bg-green-600",
  "Laravel": "bg-red-600",
  "Ruby on Rails": "bg-pink-400",
  "ASP.NET": "bg-blue-600",
  "Redux": "bg-purple-600",
  "Gatsby": "bg-teal-600",
  "Meteor.js": "bg-blue-700",
  "Svelte": "bg-orange-500",

  // Database Technologies
  "MySQL": "bg-blue-800",
  "MongoDB": "bg-green-700",
  "PostgreSQL": "bg-blue-600",
  "SQLite": "bg-gray-700",
  "Redis": "bg-red-600",
  "Cassandra": "bg-purple-700",
  "Firebase": "bg-yellow-500",
  "Oracle": "bg-amber-600",

  // Cloud & DevOps
  "AWS": "bg-orange-500",
  "Azure": "bg-blue-400",
  "Google Cloud": "bg-blue-600",
  "Docker": "bg-blue-800",
  "Kubernetes": "bg-green-700",
  "Terraform": "bg-yellow-600",
  "Jenkins": "bg-orange-600",
  "CircleCI": "bg-teal-400",
  "GitLab": "bg-gray-600",
  "GitHub": "bg-gray-700",
  "Vagrant": "bg-red-500",

  // Version Control
  "Git": "bg-gray-600",
  "SVN": "bg-blue-400",
  "Mercurial": "bg-green-500",

  // Tools & Utilities
  "Webpack": "bg-gray-800",
  "Babel": "bg-yellow-500",
  "npm": "bg-green-600",
  "Yarn": "bg-blue-500",
  "Vite": "bg-orange-400",
  "ESLint": "bg-red-600",
  "Prettier": "bg-purple-600",
  "Husky": "bg-blue-700",
  "Parcel": "bg-yellow-600",

  // Design & UX
  "UI/UX": "bg-pink-500",
  "Figma": "bg-blue-500",
  "Sketch": "bg-gray-700",
  "Adobe XD": "bg-indigo-500",
  "InVision": "bg-purple-600",
  "Zeplin": "bg-green-600",
  "Illustrator": "bg-yellow-700",
  "Photoshop": "bg-red-500",
  "Canva": "bg-teal-500",

  // Web Technologies & Protocols
  "HTML5": "bg-orange-600",
  "CSS3": "bg-indigo-600",
  "HTTP": "bg-blue-600",
  "REST API": "bg-blue-400",
  "GraphQL": "bg-pink-600",
  "WebSocket": "bg-blue-800",
  "WebAssembly": "bg-green-500",
  "JSON": "bg-yellow-500",
  "XML": "bg-purple-600",
  "WebRTC": "bg-red-500",

  // Testing & Quality Assurance
  "Jest": "bg-blue-700",
  "Mocha": "bg-gray-600",
  "Chai": "bg-green-500",
  "Cypress": "bg-indigo-500",
  "Selenium": "bg-yellow-600",
  "Karma": "bg-teal-400",
  "Puppeteer": "bg-purple-500",
  "TestCafe": "bg-red-600",

  // Security & Cryptography
  "OAuth": "bg-green-600",
  "JWT": "bg-yellow-500",
  "SSL/TLS": "bg-blue-700",
  "Encryption": "bg-indigo-700",
  "Blockchain": "bg-gray-800",
  "Hacking": "bg-red-800",
  "Penetration Testing": "bg-purple-600",

  // Artificial Intelligence & Machine Learning
  "AI": "bg-pink-600",
  "Machine Learning": "bg-green-600",
  "Deep Learning": "bg-blue-700",
  "Neural Networks": "bg-indigo-600",
  "TensorFlow": "bg-orange-500",
  "PyTorch": "bg-red-600",
  "Scikit-learn": "bg-yellow-500",
  "Keras": "bg-purple-500",
  "Natural Language Processing": "bg-teal-500",
  "Computer Vision": "bg-blue-800",

  // Big Data & Data Engineering
  "Big Data": "bg-blue-600",
  "Hadoop": "bg-orange-600",
  "Spark": "bg-red-500",
  "Kafka": "bg-gray-700",
  "ETL": "bg-green-600",
  "Data Science": "bg-blue-700",
  "Apache Flink": "bg-indigo-500",
  "Data Lake": "bg-teal-400",

  // Other Tags
  "Open Source": "bg-purple-500",
  "Agile": "bg-blue-700",
  "Scrum": "bg-green-500",
  "DevOps": "bg-yellow-500",
  "CI/CD": "bg-teal-500",
  "Cloud Computing": "bg-orange-600",
  "IoT": "bg-blue-800",
  "5G": "bg-purple-700",
  "Quantum Computing": "bg-green-700",
  "Virtual Reality": "bg-blue-600",
  "Augmented Reality": "bg-indigo-600",
  "Cybersecurity": "bg-red-700",
  "Automation": "bg-gray-600",
  "Serverless": "bg-teal-500",
  "Edge Computing": "bg-orange-500",
  "SaaS": "bg-indigo-500",
  "PaaS": "bg-blue-600",
  "IaaS": "bg-green-600",
};

